### PR TITLE
#242 adding dropdown to mmr

### PR DESCRIPTION
**Pull request by jensk1**
This is the implementation for feature https://github.com/w3champions/w3champions-ui/issues/242 
The Backend feature already has a Pull request in statistics service: https://github.com/w3champions/w3champions-statistic-service/pull/90

I reused the already existing components for the selections, as you can see the distribution changes for different selections:
1vs1
2vs2

America multiplayer looks kind of weird, but I think its just how it is: 
2vsUS

Nonetheless some one should code review this!
I had to create a new interface interface SeasonGameModeGateWayForMMR in Overallstatistics Type, because the actionhandling only allow one parameter Object (Payload). This is the wrapper for it.

If something needs to be changed, let me know.

### CODE REVIEW

**Comment by jj-apps** [comment]
There is another dropdown for game already on the Profile/Match History screen that matches the same style:
image

**Comment by modmoto** [comment]
jeah, that would be nicer, other than that, it seems solid.

**Comment by jensk1** [comment]
I Changed it now to the dropdown. Some more code, but I agree it is more intuitiv.
Also I added that the default values will be display. Season 4 was selected by default but it was not shown.
Default gamemode ist 1v1 and shown now aswell. Default Gateway is Europe
dropdownPreselect

**Comment by modmoto** [comment]
nice one, is this ready? I will update the test db aswell, so we have nicer data there.

**Comment by jensk1** [comment]
From my side it is finished. If someone has reviewed it, you can go ahead :)

**Comment by modmoto** [comment]
ok, lets see how this does on test =)

**Pull request merged**
