### PR TITLE
Ffa matches

### PR DESCRIPTION
**Pull request by jj-apps**
#205 
image

### CODE REVIEW

**Comment by Cepheid-UK** [comment]
Tested the functionality and it works great, thanks.

Would you mind tidying up the CSS a little, bringing the columns closer together? They are a remenant of me trying to fit as much info in a small a space as possible.

functionality

**Comment by jj-apps** [comment]
> Tested the functionality and it works great, thanks.
> 
> Would you mind tidying up the CSS a little, bringing the columns closer together? They are a remenant of me trying to fit as much info in a small a space as possible.
> 

Yes, will do!

**Comment by Cepheid-UK** [comment]
Also, check your @s in the w3c discord ;)

**Comment by jj-apps** [comment]
I removed all the FFA specific widths

**Comment by Cepheid-UK** [comment]
Checked and looks good!

ffa

**Pull request merged**
