### PR TITLE
Player MMR Timeline: Fixes LineChart.vue and adds rounding for Chart

### PR DESCRIPTION
**Pull request by weidenbach**
Fixes LineChart.vue gradient build error.
Adds PlayerMmrTimelineChart rounding for consistency with other charts.

### CODE REVIEW

**Comment by modmoto** [comment]
just a quick question: will the backend do the aggregation of matches per day?

**Comment by weidenbach** [comment]
Not yet, but I already programmed that and will create a PR today.

**Comment by weidenbach** [comment]
I chose to take the highest mmr per day instead of an average or that last mmr, because it can be confusing when a player knows that his highest mmr was X but its not displayed in the graph.

**Comment by modmoto** [comment]
not the last one? or average? The highest might lead to a distorted statistic, because you will have the most optimal statistic there.

**Comment by weidenbach** [comment]
Hm, you made me reassess. I think you're right. While the highest is nice for the individual player, it doesn't depict the most accurate mmr. If we trust in the mmr system then the latest mmr should be the most accurate, as the system had more games to rate the player.

**Pull request merged**
